-- rambler up

CREATE TABLE team_match (
    id bigserial PRIMARY KEY,
    team bigserial REFERENCES team(id) NOT NULL,
    match bigserial REFERENCES match(id) NOT NULL,
    rating NUMERIC(6,3),
    PossessionPercentage NUMERIC(6,3),
    Goals SMALLINT,
    OwnGoals SMALLINT,
    OwnGoalAccrued SMALLINT,
    AttPenGoal SMALLINT,
    Touches SMALLINT,
    UnsuccessfulTouch SMALLINT,
    GoalAssist SMALLINT,
    TotalPass SMALLINT,
    AccuratePass SMALLINT,
    TotalThroughBall SMALLINT,
    AccurateThroughBall SMALLINT,
    TotalFinalThirdPasses SMALLINT,
    SuccessfulFinalThirdPasses SMALLINT,
    TotalAttAssist SMALLINT,
    OffTargetAttAssist SMALLINT,
    BigChanceCreated SMALLINT,
    TotalOffside SMALLINT,
    Dispossessed SMALLINT,
    TotalScoringAtt SMALLINT,
    BlockedScoringAtt SMALLINT,
    OnTargetScoringAtt SMALLINT,
    ShotOffTarget SMALLINT,
    PostScoringAtt SMALLINT,
    BigChanceMissed SMALLINT,
    TotalTackle SMALLINT,
    LastManTackle SMALLINT,
    TotalClearance SMALLINT,
    EffectiveClearance SMALLINT,
    SixYardBlock SMALLINT,
    ClearanceOffLine SMALLINT,
    ErrorLeadToGoal SMALLINT,
    ErrorLeadToShot SMALLINT,
    Interception SMALLINT,
    InterceptionWon SMALLINT,
    BallRecovery SMALLINT,
    CornerTaken SMALLINT,
    TotalThrows SMALLINT,
    PenaltyConceded SMALLINT,
    FkFoulWon SMALLINT,
    FkFoulLost SMALLINT,
    YellowCard SMALLINT,
    RedCard SMALLINT,
    AerialLost SMALLINT,
    AerialWon SMALLINT,
    DuelLost SMALLINT,
    DuelWon SMALLINT,
    WonContest SMALLINT,
    TotalContest SMALLINT,
    penaltySave SMALLINT);

-- rambler down

DROP TABLE team_match;
